#!/usr/bin/env python3
'''
Write a script that lists all documents with name starting by Holberton in the collection school:

    The database name will be passed as option of mongo command
'''

from pymongo import MongoClient
import re

client = MongoClient('mongodb://127.0.0.1:27017')
db = client.my_db

regex = re.compile('^Holberton')
return db.school.find({"name": regex})